name: Flutter Deploy CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make deploy
      run: make deploy OUTPUT=lsvsearchdeployment
